[package]
name = "radiko-rs"
version = "0.1.1"
authors = ["h49k"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.0.1"
substring = "1.4.5"
base64 = "0.13.0"
subprocess = "0.2.6"
m3u8-rs = "1.0.7"
